default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: postgres


development:
  <<: *default
  database: onebit_exchange_development


test:
  <<: *default
  database: onebit_exchange_test
 

production:
  <<: *default
  database: onebit_exchange_production
  username: onebit_exchange
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>